export const CATEGORIES = [
  "Music",
  "Concert",
  "Workshop",
  "Sports",
  "MMA",
  "Boxing",
  "Combat Sports",
  "Wrestling",
  "Festival",
  "Clubbing",
  "Party",
  "Art",
  "Exhibition",
  "Theatre",
  "Comedy",
  "Tech",
  "Conference",
  "Gaming",
  "Esports",
  "Education",
  "Seminar",
  "Travel",
  "Adventure",
  "Photography",
  "Film",
  "Fashion",
  "Community",
  "Networking",
  "Startup",
  "Other"
];

export const CATEGORY_ICONS = {
  "Music": "Music",
  "Concert": "Mic2",
  "Workshop": "PenTool",
  "Sports": "Trophy",
  "MMA": "Swords",
  "Boxing": "Swords",
  "Combat Sports": "Swords",
  "Wrestling": "Swords",
  "Festival": "Sparkles",
  "Clubbing": "Zap",
  "Party": "Rocket",
  "Art": "Palette",
  "Exhibition": "Eye",
  "Theatre": "Masks",
  "Comedy": "Smile",
  "Tech": "Cpu",
  "Conference": "Users",
  "Gaming": "Gamepad2",
  "Esports": "Zap",
  "Education": "Book",
  "Seminar": "Presentation",
  "Travel": "Map",
  "Adventure": "Mountain",
  "Photography": "Camera",
  "Film": "Film",
  "Fashion": "Shirt",
  "Community": "UserPlus",
  "Other": "MoreHorizontal"
};
